[package]

name = "fsevent"
version = "0.2.18"
authors = [ "Pierre Baillet <pierre@baillet.name>" ]
description = "Rust bindings to the fsevent-sys OSX API for file changes notifications"
license="MIT"
repository = "https://github.com/octplane/fsevent-rust"

[lib]
name = "fsevent"
test = false
doc = true

[dependencies.fsevent-sys]
path = "fsevent-sys"
version = "0.1.7"

[dependencies]
bitflags = "0.7.0"
libc = "0.2.20"

[dev-dependencies]
tempdir = "^0.3.4"
time = "~0.1.34"
