[package]

name = "fsevent"
version = "1.0.2"
authors = [ "Pierre Baillet <pierre@baillet.name>" ]
description = "Rust bindings to the fsevent-sys macOS API for file changes notifications"
license="MIT"
repository = "https://github.com/octplane/fsevent-rust"

[dependencies]
bitflags = "1"
fsevent-sys = "2.1.0"

[dev-dependencies]
tempdir = "^0.3.4"
time = "~0.1.34"
