[package]

name = "fsevent"
version = "0.4.0"
authors = [ "Pierre Baillet <pierre@baillet.name>" ]
description = "Rust bindings to the fsevent-sys macOS API for file changes notifications"
license="MIT"
repository = "https://github.com/octplane/fsevent-rust"

[dependencies.fsevent-sys]
path = "fsevent-sys"
version = "2.0.0"

[dependencies]
bitflags = "1"

[dev-dependencies]
tempdir = "^0.3.4"
time = "~0.1.34"
