[package]

name = "fsevent"
version = "0.2.6"
authors = [ "Pierre Baillet <pierre@baillet.name>" ]
description = "Rust bindings to the fsevent-sys OSX API for file changes notifications"
license-file = "LICENSE"
repository = "https://github.com/octplane/fsevent-rust"

[lib]
name = "fsevent"
test = false
doc = true

[dependencies.fsevent-sys]
path = "fsevent-sys"
version = "~0.1.0"
